
services:
  traefik:
    image: traefik:v3.5.1
    restart: always
    command:
      - "--configFile=/static-traefik.yml"
    env_file:
      - .env
    ports:
      - 8088:8080
      - 9443:9443
      - 443:443
    environment:
    - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./static-traefik.yml:/static-traefik.yml:ro
      - ./dynamic:/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ./logs:/var/log/traefik # Volume to store Traefik logs
      - ./pki:/etc/traefik/pki:ro
    container_name: traefik
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - proxy_net
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy_net
    depends_on:
      - traefik

  cloudflare-tunnel-auto:
    image: haemeto/traefik-cloudflare-tunnel-auto
    container_name: cloudflare-tunnel-auto
    restart: unless-stopped
    env_file:
      - .env
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_TUNNEL_ID: ${CLOUDFLARE_TUNNEL_ID}
      TRAEFIK_SERVICE_ENDPOINT: ${TRAEFIK_SERVICE_ENDPOINT}
      TRAEFIK_API_ENDPOINT: ${TRAEFIK_API_ENDPOINT}
      TRAEFIK_ENTRYPOINTS: ${TRAEFIK_ENTRYPOINTS}
      POLL_INTERVAL: 10s
      SKIP_TLS_ROUTES: false
      LOG_LEVEL: debug
    networks:
      - proxy_net
    depends_on:
      - traefik
      - cloudflared

  app:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
    name: proxy_net
    enable_ipv6: true