entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  office:
    address: ":9443"

providers:
  file:
    directory: "/dynamic"
    watch: true
  # http:
  #   endpoint: "<endpoint with json dynamic config>"
  #   pollInterval: "10s"
  #   tls:
  #     insecureSkipVerify: false  

log:
  level: "DEBUG"
  # filePath: "/var/log/traefik/traefik.log"
  format: "common"
  maxSize: 100
  maxBackups: 3
  maxAge: 3
  compress: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  filters:
    statusCodes: 
     - "204-299"
     - "400-499"
     - "500-599"
     
certificatesResolvers:
  cloudflare:
    acme:
      email: <your-email>
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

api:
  dashboard: true
  insecure: true
